Detail view controller scroll view
DVT/showcase-ios pull request #9
Opened 2018-04-11 08:03 UTC by Slavitor

Adding UIViewController with scrollView. ScrollView has three placeholder UIViews that will host subviews.
Adding UIViewController extension that will handle viewController presentation. All custom presentation code for UIViewControllers will be in this extension.

2018-04-11 12:40 UTC, pjwelcome requested changes

2018-04-11 12:40 UTC, pjwelcome commented on DVTShowcase/AppDetailViewController.swift
> +        super.didReceiveMemoryWarning()
remove this if you are not using it.

2018-04-11 12:40 UTC, pjwelcome commented on DVTShowcase/AppDetailViewController.swift
> +    init(with dvtApp:[String: AnyObject?]) {
Why is this a dictionary? can you not just pass the fail why do you need to pass the whole dictionary to the next viewcontroller

2018-04-12 11:38 UTC, AntagonistBob approved these changes

2018-04-13 05:00 UTC, pjwelcome commented on DVTShowcase/AppDetailViewController.swift
> +        print(dvtApp)
removed print. Dont leave logging on anything in the code.

2018-04-13 05:00 UTC, pjwelcome approved these changes

2018-04-13 05:02 UTC, pjwelcome commented
One last thing is that you didnt need to make 11 commits for this PR. Please try and keep it less commit as possible, just way to many for this little amount of code.

2018-04-13 05:02 UTC, merged